Webappservices swagger document
ni/systemlink-OpenAPI-documents pull request #47
Opened 2019-04-16 07:17 UTC by roivinir

Adding SLC webappservices swagger document

2019-11-25 22:04 UTC, mollykreis reviewed
I didn't look over this document completely, but I did notice a few things while reading the swagger document.

2019-11-25 22:04 UTC, mollykreis commented on webapp/webappservices.yaml
> +        description: List of policy IDs associated with the webapp giving it permissions to the user's SistemllinkCloud resources"
SistemllinkCloud -> SystemLink Cloud

This is done a few places throughout this document

2019-11-25 22:04 UTC, mollykreis commented on webapp/webappservices.yaml
> +      description: Get webapp metadata by Id
We should be consistent between ID and Id.

2019-11-25 22:04 UTC, mollykreis commented on webapp/webappservices.yaml
> +        description: The webapp's
Looks like you're missing part of this description

2019-11-25 22:04 UTC, mollykreis commented on webapp/webappservices.yaml
> +      description: List users webapps
Lists the user's webapps

2019-11-25 22:04 UTC, mollykreis commented on webapp/webappservices.yaml
> +  "/webapps":
The query parameters for this route should be documented.

Same for any other route that has query parameters.

2019-11-25 22:04 UTC, mollykreis commented on webapp/webappservices.yaml
> +  WebappRecord:
From using the API, it looks like this also has created and updated timestamps. They should be documented here.

2019-11-25 22:04 UTC, mollykreis commented on webapp/webappservices.yaml
> +          description: Ivalid webapp record
Ivalid -> Invalid

2019-11-25 22:04 UTC, mollykreis commented on webapp/webappservices.yaml
> +        description: A map of key value proeprties associated with the webapp
proeprties -> properties

2019-11-25 22:04 UTC, mollykreis commented on webapp/webappservices.yaml
> +        description: Custom message to embedd in the email notification sent out to newly added emails in the sharedEmails property when the shared property is direct
embedd -> embed

The formatting of the last part of this sentence is inconsistent with other places in this document:
_From line 283: Applies when "shared" option is "direct"_

2019-11-25 22:04 UTC, mollykreis commented on webapp/webappservices.yaml
> +  UpdateWebappMetadatReuqest:
Metadat -> Metadata
Reuqest -> Request

2019-11-26 02:01 UTC, alexweav requested changes

2019-11-26 02:01 UTC, alexweav commented on webapp/webappservices.yaml
> +        - Webapp metadata
No need to prefix the sections with "webapp" since they're viewed in the context of the webapp service. They can just be `metadata` and `content` respectively.

2019-11-26 02:01 UTC, alexweav commented on webapp/webappservices.yaml
> +      summary: ''
Can summaries be added to all routes? It appears as the top-level description of the route before the user expands it, and is really helpful when reading the documentation. It appears like in this screenshot:

![image](https://user-images.githubusercontent.com/8410871/69592230-e8114100-0fba-11ea-85ab-1e1fd4a9444d.png)

Generally, the summary is shorter than the description, because the description only appears when the route is clicked on. Usually, the summary would be something like "Gets metadata for a webapp" where the description would be a full sentence with a bit more detail like "Gets metadata for a single webapp by ID."

2019-11-26 02:01 UTC, alexweav commented on webapp/webappservices.yaml
> +    post:
Seems odd for a POST route to have no parameters at all. Shouldn't there be a way to pass in webapp data when creating a new one?

2019-11-26 02:01 UTC, alexweav commented on webapp/webappservices.yaml
> +      parameters:
A bit of a nitpick, but it reads strangely to have parameters below responses, it feels like responses should come after. Feel free to ignore this one if you disagree, though.

2019-11-26 02:01 UTC, alexweav commented on webapp/webappservices.yaml
> +        type: object
Usually, the pattern for this is something like:

```
      properties:
        description: Key-value pairs associated with the webapp.
        type: object
        additionalProperties:
          type: string
        example:
          key1: value1
```

That way, example values show up correctly. If you don't do the `additionalProperties` thing, the code generators in some languages will try to replace this with a generic object, rather than the string-map equivalent that is supposed to represent properties.

2019-11-26 02:01 UTC, alexweav commented on webapp/webappservices.yaml
> +  WebappContent:
Can you add an example here? If it shows up as base64 data, add a random base64 string. Otherwise, use a different placeholder string like "Webapp content." Right now, the example in documentation is just the word "string" which I don't think conveys the right message.

2019-11-26 02:01 UTC, alexweav commented on webapp/webappservices.yaml
> +          name: webapp-binary-content
Metadata isn't binary content, right? This might need to be renamed.

2019-11-26 02:01 UTC, alexweav commented on webapp/webappservices.yaml
> +          description: API key is missing or invalid
Usually, we add a top-level `responses` section to the document which contains something like:

```
responses:
  Unauthorized:
    description: API key is missing or invalid
    headers:
      WWW_Authenticate:
        description: Information for how to authenticate
        type: string
```

Then, reference it like:

```
      responses:
        401:
          $ref: '#/responses/Unauthorized'
```

This makes it show up a bit cleaner in the documentation:

![image](https://user-images.githubusercontent.com/8410871/69593123-e006d080-0fbd-11ea-9c7c-be1c03a6143a.png)

(except it will have your description text instead of "Not Authorized - this was just the example I found)

2019-11-26 02:01 UTC, alexweav commented on webapp/webappservices.yaml
> +        description: List of policy IDs associated with the webapp giving it permissions to the user's SistemllinkCloud resources"
"webapp giving it permissions" -> "webapp, which give it access"

2020-02-21 14:23 UTC, tschmittni reviewed
I posted an update here: https://github.com/ni/systemlink-OpenAPI-documents/pull/69

2020-02-21 14:23 UTC, closed without merging