Add missing query fields to alarm API document
ni/systemlink-OpenAPI-documents pull request #54
Opened 2019-06-19 16:05 UTC by spanglerco

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/systemlink-OpenAPI-documents/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Adds the `description` and `resourceType` query fields to the alarm API document.

### Why should this Pull Request be merged?

These fields exist on the current API but were missed in the document.

### What testing has been done?

Made requests using the two new properties and verified they correctly affect the query results.

2019-06-19 16:24 UTC, pvallone submitted a review, later dismissed

2019-06-24 14:56 UTC, caleyburton requested changes

2019-06-24 14:56 UTC, caleyburton commented on alarm/nialarm.yml
> +          contain the description query string, without taking case into account.
Could we split the second sentence into two? I'd like the third sentence say something like, "This query does not take casing into account." This goes for all applicable instances.

2019-06-24 17:48 UTC, caleyburton approved these changes

2019-06-24 18:47 UTC, merged