Initial commit of the nitdmreader.yml swagger doc
ni/systemlink-OpenAPI-documents pull request #8
Opened 2018-09-07 16:59 UTC by BKnight760

Initial commit of the nitdmreader.yml swagger doc.  This is used by the TDM Reader service, but is not code-generated into a a webservice interface yet.

[x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/systemlink-OpenAPI-documents/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This pull request adds a Swagger document for the TDM Reader service. This will be the master copy of the TDM Reader service's Swagger document, for use in SystemLink Server.

### Why should this Pull Request be merged?

This pull request gives higher visibility to the TDM Reader HTTP API.

### What testing has been done?

Existing automated tests have been run against webservice, and all tests pass.

2018-09-10 15:19 UTC, spanglerco requested changes

2018-09-10 15:19 UTC, spanglerco commented on tdm-reader/nitdmreader.yml
> +  FileList:
This doesn't have the latest change made last Thursday that wraps this in an object.

2018-09-11 18:37 UTC, adelcast commented
Should we change the section name for Properties to something more meaningful like Metadata? The problem is that Properties already have a meaning (Channels, Files and Groups have properties). The query-files endpoint returns metadata as well as properties (maybe the endpoint name should change too?)

2018-09-11 19:10 UTC, spanglerco submitted a review, later dismissed

2018-09-11 21:19 UTC, jjaco2 reviewed
Just some questions to clarify wording and some notes for consistency.

In addition to the things I noted, consider removing periods from any descriptions that aren't a complete sentence. This seems to be the industry-standard way to punctuate in these documents.

2018-09-11 21:19 UTC, jjaco2 commented on tdm-reader/nitdmreader.yml
> +        description: File Ids
IDs

2018-09-11 21:19 UTC, jjaco2 commented on tdm-reader/nitdmreader.yml
> +        description: Number of pixels on the x axis which is the number of points that can be displayed.
Number of pixels on the x axis. This determines the number of points that can be displayed.

2018-09-11 21:19 UTC, jjaco2 commented on tdm-reader/nitdmreader.yml
> +        description: Number of pixels on the y axis which is the number of points that can be displayed
Number of pixels on the y axis. This determines the number of points that can be displayed.

2018-09-11 21:19 UTC, jjaco2 commented on tdm-reader/nitdmreader.yml
> +        description: Minimum X value of the display X axis.
Do we want to capitalize X/Y or no? Either is fine, just need to make sure they're consistent. They're capitalized here, but not above.

2018-09-11 21:19 UTC, jjaco2 commented on tdm-reader/nitdmreader.yml
> +        description: Decimate to point style graph.
Here and in the previous description, I'm not sure even after some googling what decimate means in this context. Is there a way we could put this in plainer terms for newer users? "Represent data as a point-style graph" or something?

2018-09-11 21:19 UTC, jjaco2 commented on tdm-reader/nitdmreader.yml
> +    description: Specification for an array of groups of channels potentially with x-y relationships.
Could "groups of channels" be "channel groups?" That'd get rid of one of the prepositional phrases and make this a little easier to follow.

Also curious what "potentially" means here, so there's an opportunity for more clarity. Does it mean the groups of channels support these relationships?

2018-09-11 21:19 UTC, jjaco2 commented on tdm-reader/nitdmreader.yml
> +    description: Channel specifications and data window.
Can remove period

2018-09-11 21:19 UTC, jjaco2 commented on tdm-reader/nitdmreader.yml
> +        description: Native data type of data
Maybe "Native data type for the channel" or "Native data type of data in the channel"

2018-09-11 21:19 UTC, jjaco2 commented on tdm-reader/nitdmreader.yml
> +        description: is returned data decimated
Specifies whether returned data is decimated [though again, there might be a clearer way to describe decimation]

2018-09-11 21:19 UTC, jjaco2 commented on tdm-reader/nitdmreader.yml
> +        description: channel data
Capital C to match capitalization in other descriptions. This is one of those things that doesn't _really_ matter, but consistency is a good way to build trust with the power Swagger user type.

2018-09-11 21:19 UTC, jjaco2 commented on tdm-reader/nitdmreader.yml
> +        description: number of points of undecimated data
Number

2018-09-11 21:19 UTC, jjaco2 commented on tdm-reader/nitdmreader.yml
> +        description: y channels
Depending on whether you decide to capitalize x and y throughout, might want to capitalize Y here.

2018-09-11 21:19 UTC, jjaco2 commented on tdm-reader/nitdmreader.yml
> +        description: The timezone offset applied to local time values
time zone

2018-09-11 21:19 UTC, jjaco2 commented on tdm-reader/nitdmreader.yml
> +    description: A list of names and a count of all names.
"List.." is fine

2018-09-11 21:19 UTC, jjaco2 commented on tdm-reader/nitdmreader.yml
> +        description: Count of all items in the list. This could be more than the items returned in Names.
Total number of items in the list. This might be more than the number names.

2018-09-11 21:19 UTC, jjaco2 commented on tdm-reader/nitdmreader.yml
> +          description: Specify this to return the total count of items
Specifies whether to return the total number of items

2018-09-11 21:19 UTC, jjaco2 commented on tdm-reader/nitdmreader.yml
> +      summary: Lists all channels in the group
Other Swagger documents I've reviewed have both a summary and description. Is there a specific reason to only have summary? I don't know a ton about implementation. Could maybe ask Phil about this.

2018-09-11 21:19 UTC, jjaco2 commented on tdm-reader/nitdmreader.yml
> +          description: Channel specifications and window information.
Do we expect users to know what window information is? Just something to think about

2018-09-12 20:19 UTC, BKnight760 commented on tdm-reader/nitdmreader.yml
> +    description: Specification for an array of groups of channels potentially with x-y relationships.
The wording was confusing.  The object here is an array of x-y channel groupings.  Each grouping contains 0 to 1 x-channels, and N y-channels.  The x-channel is optional, which is what the "potentially" was referring to.  Hopefully the new wording is clearer.

2018-09-17 15:35 UTC, jjaco2 approved these changes

2018-09-17 15:44 UTC, merged